version: '3'
services:
  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
    volumes:
      - /opt/homeassistant/matter/data:/data
      - /run/dbus:/run/dbus:ro
    network_mode: host
  # certbot:
  #   container_name: certbot
  #   image: ghcr.io/home-assistant-libs/python-matter-server:stable
  #   restart: unless-stopped
  #   security_opt:
  #     - apparmor=unconfined
  #   volumes:
  #     - /opt/letsencrypt:/etc/letsencrypt
  #     - /opt/homeassistant/certbot/data:/data
  #     - /run/dbus:/run/dbus:ro
  #   network_mode: host