version: '3.8'
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=Europe/Prague
    volumes:
      - /opt/homeassistant/config:/config
      - /opt/homeassistant/letsencrypt:/etc/letsencrypt:ro
      - /run/dbus:/run/dbus:ro
    network_mode: host

  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
    volumes:
      - /opt/homeassistant/matter/data:/data
      - /run/dbus:/run/dbus:ro
    network_mode: host

  zigbee2mqtt:
      container_name: zigbee2mqtt
      image: koenkk/zigbee2mqtt
      restart: unless-stopped
      volumes:
          - /opt/homeassistant/zigbee2mqtt/data:/app/data
          - /run/udev:/run/udev:ro
      ports:
          - 8080:8080
      environment:
          - TZ=Europe/Prague
      devices:
          - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_32dd67206ee7ed11970f6d6262c613ac-if00-port0:/dev/ttyACM0


  # certbot:
  #   container_name: certbot
  #   image: ghcr.io/home-assistant-libs/python-matter-server:stable
  #   restart: unless-stopped
  #   security_opt:
  #     - apparmor=unconfined
  #   volumes:
  #     - /opt/letsencrypt:/etc/letsencrypt
  #     - /opt/homeassistant/certbot/data:/data
  #     - /run/dbus:/run/dbus:ro
  #   network_mode: host